#!/usr/bin/env python3
"""
render_cue_icons.py - Two tiny static label icons, addressing the
"emoji vs APGAR" conceptual-mismatch concern: a thermometer next to the
baby's face (this row is about temperature) and a clock next to the
APGAR timer (this row is a clock reading), so the two rows read as
clearly different kinds of information at a glance.

Deliberately NOT a reuse of icons.c's existing thermometer (that one's
"on" state is red with a fault-alert badge, meant for an actual sensor
problem; its "off" state is COLOR_DIM_GREY, tuned to be quiet/inactive
and nearly invisible at this size). Both would send the wrong signal
here - this is a plain, permanent, neutral label, not a status
indicator - so it's rendered fresh in a calm white matching the
timer's normal (non-flashing) color.

16x16 was picked from the real available space: the face bitmap's
visible circle only fills the center of its 80x80 box (see baby.c),
leaving ~24px of empty margin to the right before the screen edge -
plenty for a 16px icon with a couple px to spare. The APGAR timer
leaves ~25px free to its right for the same reason.

Bold filled shapes, not thin strokes, so unlike the text console font
anti-aliasing holds up fine at this size (see render_font.py for why
that's not true of 1px-wide glyph strokes).

Output:
  out/cue_icons_contact_sheet.png -- both icons, upscaled for viewing
  ../cue_icon_bitmaps.h           -- C header with both arrays
"""
import math
import os
import cairo
from PIL import Image

SIZE = 16
SS = 10
COLOR = (1.0, 1.0, 1.0)  # plain white - neutral label, not a status/alarm color


def new_ctx():
    surf = cairo.ImageSurface(cairo.FORMAT_ARGB32, SIZE * SS, SIZE * SS)
    ctx = cairo.Context(surf)
    ctx.scale(SS, SS)
    ctx.set_operator(cairo.OPERATOR_SOURCE)
    ctx.set_source_rgba(0, 0, 0, 0)
    ctx.paint()
    ctx.set_operator(cairo.OPERATOR_OVER)
    ctx.set_line_cap(cairo.LINE_CAP_ROUND)
    ctx.set_line_join(cairo.LINE_JOIN_ROUND)
    return surf, ctx


def finish(surf):
    hires = Image.frombuffer("RGBA", (SIZE * SS, SIZE * SS), bytes(surf.get_data()), "raw", "BGRA", 0, 1)
    small = hires.resize((SIZE, SIZE), Image.LANCZOS)
    bg = Image.new("RGB", (SIZE, SIZE), (0, 0, 0))
    bg.paste(small, (0, 0), small)
    return bg


def make_thermometer():
    surf, ctx = new_ctx()
    cx = SIZE / 2
    stem_w = SIZE * 0.16
    top_y, bulb_y = SIZE * 0.12, SIZE * 0.68

    ctx.set_source_rgb(*COLOR)
    ctx.new_sub_path()
    ctx.arc(cx, top_y, stem_w / 2, math.pi, 2 * math.pi)
    ctx.rectangle(cx - stem_w / 2, top_y, stem_w, bulb_y - top_y)
    ctx.fill()
    ctx.arc(cx, bulb_y, SIZE * 0.2, 0, 2 * math.pi)
    ctx.fill()

    # thin black gap for the capsule outline look
    inner_w = stem_w * 0.45
    ctx.set_source_rgb(0, 0, 0)
    ctx.new_sub_path()
    ctx.arc(cx, top_y + SIZE * 0.05, inner_w / 2, math.pi, 2 * math.pi)
    ctx.rectangle(cx - inner_w / 2, top_y + SIZE * 0.05, inner_w, bulb_y - top_y - SIZE * 0.05)
    ctx.fill()
    ctx.arc(cx, bulb_y, SIZE * 0.12, 0, 2 * math.pi)
    ctx.fill()

    ctx.set_source_rgb(*COLOR)
    ctx.new_sub_path()
    ctx.rectangle(cx - inner_w / 2 + SIZE * 0.02, top_y + SIZE * 0.22,
                  inner_w - SIZE * 0.04, bulb_y - top_y - SIZE * 0.22)
    ctx.fill()
    ctx.arc(cx, bulb_y, SIZE * 0.10, 0, 2 * math.pi)
    ctx.fill()
    return finish(surf)


def make_clock():
    surf, ctx = new_ctx()
    cx = cy = SIZE / 2
    r = SIZE / 2 - SIZE * 0.08

    ctx.set_source_rgb(*COLOR)
    ctx.set_line_width(SIZE * 0.11)
    ctx.arc(cx, cy, r, 0, 2 * math.pi)
    ctx.stroke()
    ctx.set_line_width(SIZE * 0.10)
    ctx.move_to(cx, cy)
    ctx.line_to(cx, cy - r * 0.55)
    ctx.stroke()
    ctx.move_to(cx, cy)
    ctx.line_to(cx + r * 0.42, cy + r * 0.12)
    ctx.stroke()
    return finish(surf)


ICONS = {
    "cue_icon_thermometer": make_thermometer,
    "cue_icon_clock": make_clock,
}


def to_rgb565_words(img):
    img = img.convert("RGB")
    words = []
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = img.getpixel((x, y))
            words.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return words


def main():
    outdir = os.path.join(os.path.dirname(__file__), "out")
    os.makedirs(outdir, exist_ok=True)

    header_arrays = {}
    sheet_cells = []
    for name, fn in ICONS.items():
        img = fn()
        img.resize((SIZE * 10, SIZE * 10), Image.NEAREST).save(f"{outdir}/{name}_actual.png")
        header_arrays[name] = to_rgb565_words(img)
        sheet_cells.append((name, img))
        print(f"{name}: rendered ({SIZE}x{SIZE}, {SIZE*SIZE*2} bytes)")

    header_path = os.path.join(os.path.dirname(__file__), "..", "cue_icon_bitmaps.h")
    with open(header_path, "w") as f:
        f.write("#ifndef CUE_ICON_BITMAPS_H\n#define CUE_ICON_BITMAPS_H\n\n#include <stdint.h>\n\n")
        f.write("/* Auto-generated by input/art/render_cue_icons.py - do not edit by hand. */\n\n")
        f.write(f"#define CUE_ICON_SIZE {SIZE}\n\n")
        for name, words in header_arrays.items():
            f.write(f"const uint16_t {name}[{len(words)}] = {{\n")
            for i in range(0, len(words), 14):
                row = words[i:i + 14]
                f.write("    " + ",".join(f"0x{w:04X}" for w in row) + ",\n")
            f.write("};\n\n")
        f.write("#endif /* CUE_ICON_BITMAPS_H */\n")
    print(f"\nC header written: {os.path.abspath(header_path)}")

    scale = 10
    pad = 8
    cell = SIZE * scale + pad
    sheet = Image.new("RGB", (cell * len(sheet_cells) + pad, cell + pad), (30, 30, 30))
    for i, (name, img) in enumerate(sheet_cells):
        big = img.resize((SIZE * scale, SIZE * scale), Image.NEAREST)
        sheet.paste(big, (pad + i * cell, pad))
    sheet.save(f"{outdir}/cue_icons_contact_sheet.png")
    print(f"contact sheet: {outdir}/cue_icons_contact_sheet.png")


if __name__ == "__main__":
    main()
