#!/usr/bin/env python3
"""
render_font.py - Bake the text console's font from a real bitmap font,
not a vector font.

History: the first two versions of this font (bold, then regular
weight) rendered DejaVu Sans Mono with cairo, supersampled, then either
kept anti-aliased edges or thresholded to 1-bit - same pipeline as
icons/faces/APGAR digits. At 6 pixels wide that read as ragged: a
vector outline auto-thresholded down this far places pixels a little
inconsistently between glyphs (a stem clean in one letter, offset by a
pixel in another), which is a different problem than anti-aliasing and
anti-aliasing doesn't fix it.

Leon asked to look at what actually makes xterm's classic default font
readable at small sizes: it's not derived from a vector outline at
all - it's a bitmap font, hand-drawn pixel-by-pixel. No thresholding
noise, because there's no thresholding step.

Source: fonts/6x10.bdf - the X11 "misc-fixed" family's 6x10 regular
face, exactly what /usr/share/fonts/misc/6x10-ISO8859-1.pcf.gz ships
on most Linux distros, and the traditional source of xterm's default
font. Its own embedded COPYRIGHT property reads "Public domain terminal
emulator font.  Share and enjoy." - PCF is a compiled binary format, so
it was extracted to BDF (plain text) with pcf2bdf
(https://github.com/ganaware/pcf2bdf, itself derived from libXfont's
pcfread.c) and vendored here rather than re-extracted on every rebake,
since not every dev machine has the X11 misc-fixed package installed.

It happens to be exactly 6px wide, matching the 21-column grid already
chosen. Every glyph in this BDF shares one BBX (6 10 0 -2), i.e. its
bitmap rows/columns map 1:1 onto our 6x10 cell with no per-glyph offset
math needed - verified before relying on it (main() asserts this).

Output:
  out/font_contact_sheet.png  -- all 95 glyphs, upscaled for viewing
  ../font_bitmaps.h           -- C header, same shape as the previous
                                  cairo-based version (drop-in).
"""
import os

FONT_W, FONT_H = 6, 10
FIRST_CHAR = 32   # ' '
LAST_CHAR = 126   # '~'
EXPECTED_BBX = (FONT_W, FONT_H, 0, -2)

BDF_PATH = os.path.join(os.path.dirname(__file__), "fonts", "6x10.bdf")


def parse_bdf(path):
    """Return {codepoint: (bbx, [row_byte, ...])} for every STARTCHAR
    block - row_byte's MSB is the glyph's leftmost pixel."""
    with open(path) as f:
        lines = f.read().splitlines()

    glyphs = {}
    i = 0
    while i < len(lines):
        if lines[i].startswith("STARTCHAR"):
            encoding, bbx, rows = None, None, []
            i += 1
            while not lines[i].startswith("ENDCHAR"):
                l = lines[i]
                if l.startswith("ENCODING"):
                    encoding = int(l.split()[1])
                elif l.startswith("BBX"):
                    bbx = tuple(int(x) for x in l.split()[1:])
                elif l.startswith("BITMAP"):
                    i += 1
                    while not lines[i].startswith("ENDCHAR"):
                        rows.append(int(lines[i], 16))
                        i += 1
                    break
                i += 1
            if encoding is not None:
                glyphs[encoding] = (bbx, rows)
        i += 1
    return glyphs


def glyph_to_words(rows):
    """rows: FONT_H bytes -> FONT_W*FONT_H RGB565 words, row-major,
    white-on-black."""
    words = []
    for row_byte in rows:
        for col in range(FONT_W):
            bit = (row_byte >> (7 - col)) & 1
            words.append(0xFFFF if bit else 0x0000)
    return words


def main():
    outdir = os.path.join(os.path.dirname(__file__), "out")
    os.makedirs(outdir, exist_ok=True)

    all_glyphs = parse_bdf(BDF_PATH)

    glyphs = {}
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        if code not in all_glyphs:
            raise SystemExit(f"missing glyph 0x{code:02X} in {BDF_PATH}")
        bbx, rows = all_glyphs[code]
        if bbx != EXPECTED_BBX:
            raise SystemExit(
                f"glyph 0x{code:02X} has BBX {bbx}, expected {EXPECTED_BBX} "
                "- the 1:1 row/col mapping this script relies on doesn't hold"
            )
        glyphs[code] = rows

    header_path = os.path.join(os.path.dirname(__file__), "..", "font_bitmaps.h")
    with open(header_path, "w") as f:
        f.write("#ifndef FONT_BITMAPS_H\n#define FONT_BITMAPS_H\n\n#include <stdint.h>\n\n")
        f.write("/* Auto-generated by input/art/render_font.py from fonts/6x10.bdf "
                 "- do not edit by hand. */\n\n")
        f.write(f"#define FONT_W {FONT_W}\n#define FONT_H {FONT_H}\n")
        f.write(f"#define FONT_FIRST_CHAR {FIRST_CHAR}\n#define FONT_NUM_CHARS {LAST_CHAR - FIRST_CHAR + 1}\n\n")
        f.write("/* Indexed by (ch - FONT_FIRST_CHAR); ch outside "
                 "[FONT_FIRST_CHAR, FONT_FIRST_CHAR+FONT_NUM_CHARS) is the\n"
                 " * caller's responsibility to substitute (see text_console.c). */\n")
        f.write("const uint16_t font_bitmaps[FONT_NUM_CHARS][FONT_W * FONT_H] = {\n")
        for code in range(FIRST_CHAR, LAST_CHAR + 1):
            words = glyph_to_words(glyphs[code])
            ch = chr(code)
            comment = ch if ch not in ("\\", "'") else "\\" + ch
            f.write(f"    {{ /* 0x{code:02X} '{comment}' */\n")
            for r in range(0, len(words), 12):
                row = words[r:r + 12]
                f.write("        " + ",".join(f"0x{w:04X}" for w in row) + ",\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("#endif /* FONT_BITMAPS_H */\n")
    print(f"C header written: {os.path.abspath(header_path)}")

    # contact sheet
    from PIL import Image
    scale = 8
    per_row = 16
    pad = 2
    n = LAST_CHAR - FIRST_CHAR + 1
    rows_n = (n + per_row - 1) // per_row
    cell_w = FONT_W * scale + pad
    cell_h = FONT_H * scale + pad
    sheet = Image.new("RGB", (cell_w * per_row + pad, cell_h * rows_n + pad), (30, 30, 30))
    for i, code in enumerate(range(FIRST_CHAR, LAST_CHAR + 1)):
        r, c = divmod(i, per_row)
        words = glyph_to_words(glyphs[code])
        img = Image.new("RGB", (FONT_W, FONT_H), (0, 0, 0))
        for y in range(FONT_H):
            for x in range(FONT_W):
                if words[y * FONT_W + x]:
                    img.putpixel((x, y), (255, 255, 255))
        big = img.resize((FONT_W * scale, FONT_H * scale), Image.NEAREST)
        sheet.paste(big, (pad + c * cell_w, pad + r * cell_h))
    sheet.save(f"{outdir}/font_contact_sheet.png")
    print(f"contact sheet: {outdir}/font_contact_sheet.png")


if __name__ == "__main__":
    main()
