#!/usr/bin/env python3
"""
render_timer.py - Render the APGAR timer's digit font ('0'-'9' + ':') as
pre-baked, anti-aliased bitmaps (cairo, supersampled), same pipeline as
render_icons.py / render_faces.py.

Each glyph is baked into a fixed-size cell so the timer module can just
blit 5 cells side by side (MM:SS) without doing any text layout on-device.
Digits share one common baseline (computed from '8') so they don't jitter
vertically against each other; the colon is centered on its own ink
extents (the natural place for a clock separator).

Two color variants are baked per glyph: the normal white readout, and a
"highlight" yellow variant (same yellow as the warning icon's "on"
state) used to flash the timer around the standard APGAR checkpoints
(1 min, 5 min, 10 min after birth) - see apgar_timer.c.

Output:
  out/timer_<glyph>_actual.png   -- exact pixel output, upscaled for viewing
  out/timer_contact_sheet.png    -- all glyphs side by side
  ../digit_bitmaps.h             -- C header with all 22 arrays
"""
import os
import cairo
from PIL import Image

DIGIT_W, DIGIT_H = 10, 16
COLON_W = 6
SS = 8

FONT = "DejaVu Sans Mono"
COLOR_NORMAL    = (1.0, 1.0, 1.0)  # bright white on black - easy to retune later
COLOR_HIGHLIGHT = (1.0, 0.80, 0.0)  # same yellow as the warning icon's "on" state
BG = (0, 0, 0)


def render_glyph(ch, cell_w, color):
    sw, sh = cell_w * SS, DIGIT_H * SS
    surf = cairo.ImageSurface(cairo.FORMAT_ARGB32, sw, sh)
    ctx = cairo.Context(surf)
    ctx.set_source_rgba(0, 0, 0, 0)
    ctx.paint()

    ctx.select_font_face(FONT, cairo.FONT_SLANT_NORMAL, cairo.FONT_WEIGHT_BOLD)
    # pick a font size that fills most of the cell height
    size = DIGIT_H * SS * 1.15
    ctx.set_font_size(size)

    # common baseline for all digits, taken from '8' so 0-9 sit level;
    # the colon centers on its own extents instead (it isn't a digit).
    ref = "8" if ch != ":" else ch
    rx, ry, rw, rh, _, _ = ctx.text_extents(ref)
    baseline_y = (sh - rh) / 2 - ry

    ext = ctx.text_extents(ch)
    tx, ty, tw, th, _, _ = ext
    x = (sw - tw) / 2 - tx

    ctx.set_source_rgb(*color)
    ctx.move_to(x, baseline_y)
    ctx.show_text(ch)

    hires = Image.frombuffer("RGBA", (sw, sh), bytes(surf.get_data()), "raw", "BGRA", 0, 1)
    small = hires.resize((cell_w, DIGIT_H), Image.LANCZOS)
    bg = Image.new("RGB", (cell_w, DIGIT_H), BG)
    bg.paste(small, (0, 0), small)
    return bg


GLYPH_CHARS = {
    "digit_0": ("0", DIGIT_W),
    "digit_1": ("1", DIGIT_W),
    "digit_2": ("2", DIGIT_W),
    "digit_3": ("3", DIGIT_W),
    "digit_4": ("4", DIGIT_W),
    "digit_5": ("5", DIGIT_W),
    "digit_6": ("6", DIGIT_W),
    "digit_7": ("7", DIGIT_W),
    "digit_8": ("8", DIGIT_W),
    "digit_9": ("9", DIGIT_W),
    "digit_colon": (":", COLON_W),
}

# each base name gets a normal-color array and a "_hi" highlight-color array
GLYPHS = {}
for base_name, (ch, w) in GLYPH_CHARS.items():
    GLYPHS[base_name] = (ch, w, COLOR_NORMAL)
    GLYPHS[base_name + "_hi"] = (ch, w, COLOR_HIGHLIGHT)


def to_rgb565_words(img):
    img = img.convert("RGB")
    words = []
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = img.getpixel((x, y))
            words.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return words


def write_c_header(path, guard, arrays, meta):
    with open(path, "w") as f:
        f.write(f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n")
        f.write("/* Auto-generated by input/art/render_timer.py - do not edit by hand. */\n\n")
        f.write(f"#define DIGIT_W {meta['digit_w']}\n")
        f.write(f"#define DIGIT_H {meta['digit_h']}\n")
        f.write(f"#define COLON_W {meta['colon_w']}\n\n")
        for name, words in arrays.items():
            f.write(f"const uint16_t {name}[{len(words)}] = {{\n")
            for i in range(0, len(words), 14):
                row = words[i:i + 14]
                f.write("    " + ",".join(f"0x{w:04X}" for w in row) + ",\n")
            f.write("};\n\n")
        f.write(f"#endif /* {guard} */\n")


def main():
    outdir = os.path.join(os.path.dirname(__file__), "out")
    os.makedirs(outdir, exist_ok=True)

    header_arrays = {}
    sheet_cells = []
    for name, (ch, cell_w, color) in GLYPHS.items():
        img = render_glyph(ch, cell_w, color)
        img.resize((cell_w * 10, DIGIT_H * 10), Image.NEAREST).save(f"{outdir}/timer_{name}_actual.png")
        header_arrays[name] = to_rgb565_words(img)
        sheet_cells.append((name, img))
        print(f"{name}: rendered ({cell_w}x{DIGIT_H}, {cell_w*DIGIT_H*2} bytes)")

    header_path = os.path.join(os.path.dirname(__file__), "..", "digit_bitmaps.h")
    write_c_header(header_path, "DIGIT_BITMAPS_H", header_arrays,
                    {"digit_w": DIGIT_W, "digit_h": DIGIT_H, "colon_w": COLON_W})
    print(f"\nC header written: {os.path.abspath(header_path)}")

    # contact sheet
    scale = 10
    pad = 8
    cell_h = DIGIT_H * scale + pad + 14
    sheet_w = sum(w * scale + pad for _, (_, w, _) in GLYPHS.items()) + pad
    sheet = Image.new("RGB", (sheet_w, cell_h + pad), (30, 30, 30))
    x = pad
    for name, img in sheet_cells:
        w = img.width
        big = img.resize((w * scale, DIGIT_H * scale), Image.NEAREST)
        sheet.paste(big, (x, pad))
        x += w * scale + pad
    sheet.save(f"{outdir}/timer_contact_sheet.png")
    print(f"contact sheet: {outdir}/timer_contact_sheet.png")


if __name__ == "__main__":
    main()
