#!/usr/bin/env python3
"""
render_faces.py - Convert the 3 OpenMoji emoji faces (already fetched into
openmoji_src/, CC BY-SA 4.0 - same license already credited in this project
for the earlier emoji swap) into RGB565 bitmaps for the baby-warmer display.

Faces:
  1F60A - smiling face with smiling eyes -> BABY_OK
  1F976 - cold face                      -> BABY_COLD (and BABY_WARMING, no
                                             distinct "warming" emoji exists;
                                             reuses the cold face until told
                                             otherwise)
  1F975 - hot face                       -> BABY_HOT

Output: face_bitmaps.h with 3 arrays (face_ok, face_cold, face_hot), each
FACE_W x FACE_H RGB565 words, composited onto black.
"""
import os
import subprocess
import math
from PIL import Image

FACE_W = FACE_H = 80
SUPERSAMPLE_PX = 512  # rsvg-convert render size before downsampling

SRC = {
    "face_ok":   "1F60A",
    "face_cold": "1F976",
    "face_hot":  "1F975",
}


def rasterize(code, size):
    svg_path = f"openmoji_src/{code}.svg"
    png_path = f"out/_raw_{code}.png"
    subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), svg_path, "-o", png_path],
        check=True,
    )
    return Image.open(png_path)


def to_rgb565_words(img):
    img = img.convert("RGB")
    words = []
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = img.getpixel((x, y))
            words.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return words


def write_c_header(path, guard, arrays):
    with open(path, "w") as f:
        f.write(f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n")
        f.write("/* Auto-generated by input/art/render_faces.py - do not edit by hand. */\n\n")
        for name, words in arrays.items():
            f.write(f"const uint16_t {name}[{len(words)}] = {{\n")
            for i in range(0, len(words), 12):
                row = words[i:i + 12]
                f.write("    " + ",".join(f"0x{w:04X}" for w in row) + ",\n")
            f.write("};\n\n")
        f.write(f"#endif /* {guard} */\n")


def main():
    outdir = os.path.join(os.path.dirname(__file__), "out")
    os.makedirs(outdir, exist_ok=True)

    header_arrays = {}
    for name, code in SRC.items():
        hires = rasterize(code, SUPERSAMPLE_PX).convert("RGBA")
        small = hires.resize((FACE_W, FACE_H), Image.LANCZOS)
        bg = Image.new("RGB", (FACE_W, FACE_H), (0, 0, 0))
        bg.paste(small, (0, 0), small)
        bg.resize((FACE_W * 4, FACE_H * 4), Image.NEAREST).save(f"{outdir}/{name}_actual.png")
        header_arrays[name] = to_rgb565_words(bg)
        print(f"{name} ({code}): {FACE_W}x{FACE_H}, {len(header_arrays[name]) * 2} bytes")

    header_path = os.path.join(os.path.dirname(__file__), "..", "face_bitmaps.h")
    write_c_header(header_path, "FACE_BITMAPS_H", header_arrays)
    print(f"\nC header written: {os.path.abspath(header_path)}")


if __name__ == "__main__":
    main()
